=begin
#iDroit Dashboard Admin API

#     これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   

OpenAPI spec version: 0.9.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::DidInfosApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DidInfosApi' do
  before do
    # run before each test
    @instance = SwaggerClient::DidInfosApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DidInfosApi' do
    it 'should create an instance of DidInfosApi' do
      expect(@instance).to be_instance_of(SwaggerClient::DidInfosApi)
    end
  end

  # unit tests for did_infos_controller_add_label
  # DID情報へのラベル追加
  # リクエストパラメータのidで指定された単一のDID情報に対して、任意の管理用ラベルを追加します。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DidInfoResponseDto]
  describe 'did_infos_controller_add_label test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_connect_user
  # DID情報へのクライアントアカウント紐付け
  # DID情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
  # @param id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [DidInfoResponseDto]
  describe 'did_infos_controller_connect_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_create
  # 新規DID生成
  # 新規DIDを生成します。
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'did_infos_controller_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_disconnect_user
  # DID情報のクライアントアカウント紐付け解除
  # DID情報に紐付いたクライアントアカウントの紐付けを解除します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'did_infos_controller_disconnect_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_find_all
  # DID情報一覧取得
  # アプリケーションが管理するDID情報を一覧として値を返します。
  # @param [Hash] opts the optional parameters
  # @option opts [BigDecimal] :page (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
  # @option opts [BigDecimal] :limit (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
  # @option opts [String] :did (任意) 例: \&quot;did:key:z6MkhGeGj7u5htkCYjE4PaQ8HUqjYyTmxpDb6Q1MqUpUDsN7\&quot;
  # @option opts [String] :manage_uuid (任意) 例: \&quot;32bad62a-4186-4d04-a26a-fcee79d5824b\&quot;
  # @option opts [String] :label (任意) 例: \&quot;did-for-project1\&quot;
  # @option opts [String] :method (任意) 例: \&quot;did:key
  # @option opts [BOOLEAN] :exist_private_key (任意) 例: true
  # @option opts [String] :description (任意) 
  # @option opts [String] :domain_name (任意) 例: \&quot;did:web:idroit-dashboard.com\&quot;
  # @return [DidInfosResponseDto]
  describe 'did_infos_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_find_one
  # DID情報詳細取得
  # リクエストパラメータのidで指定された単一のDID情報の詳細情報の値を返します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DidInfoResponseDto]
  describe 'did_infos_controller_find_one test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_register
  # 既存DID登録
  # 外部で生成されたDIDを本アプリケーションに取り込みます。
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'did_infos_controller_register test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_remove
  # DID情報削除
  # リクエストパラメータのidで指定された単一のDID情報を削除します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'did_infos_controller_remove test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for did_infos_controller_resolve
  # DID解決
  # DIDを解決した結果であるDID Documentの値を返します。このAPIでは保存などの処理を行いません。生成済みのDIDを保存したい場合、既存DID登録API(/did-infos/register)にリクエストを送信してください。
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [ResolveDidResponseDto]
  describe 'did_infos_controller_resolve test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
