=begin
#iDroit Dashboard Admin API

#     これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   

OpenAPI spec version: 0.9.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::FilesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FilesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::FilesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FilesApi' do
    it 'should create an instance of FilesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::FilesApi)
    end
  end

  # unit tests for files_controller_download
  # ファイルダウンロード
  # リクエストパラメータのidで指定された単一のファイルのバイナリデータを返します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [String]
  describe 'files_controller_download test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_controller_execute_csv
  # CSVファイル実行
  # (非推奨) ユーザー、クライアント情報を記載したCSVファイルを実行し、新規アカウントを作成します。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'files_controller_execute_csv test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_controller_find_all
  # ファイル一覧取得
  # ファイルを一覧として値を返します。
  # @param [Hash] opts the optional parameters
  # @option opts [BigDecimal] :page (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
  # @option opts [BigDecimal] :limit (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
  # @option opts [String] :filename (任意) 例: \&quot;file-1732019975229-394515535.png\&quot;
  # @option opts [String] :originalname (任意) 例: \&quot;english-badge.png\&quot;
  # @option opts [BOOLEAN] :executed (任意) 例: true
  # @option opts [String] :type (任意) 例: \&quot;image/png\&quot;
  # @option opts [BigDecimal] :status (任意) 例: 0
  # @return [FilesResponseDto]
  describe 'files_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_controller_find_one
  # ファイル詳細取得
  # リクエストパラメータのidで指定された単一のファイルの詳細情報の値を返します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [FileResponseDto]
  describe 'files_controller_find_one test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_controller_remove
  # ファイル削除
  # リクエストパラメータのidで指定された単一のファイルを削除します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'files_controller_remove test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for files_controller_upload_file
  # ファイルアップロード
  # 新規ファイルアップロードを作成します。
  # @param file 
  # @param [Hash] opts the optional parameters
  # @return [FileResponseDto]
  describe 'files_controller_upload_file test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
