=begin
#iDroit Dashboard Admin API

#     これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   

OpenAPI spec version: 0.9.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::GroupsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GroupsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::GroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GroupsApi' do
    it 'should create an instance of GroupsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::GroupsApi)
    end
  end

  # unit tests for groups_controller_connect_did_infos
  # グループへのDID情報紐付け
  # グループにDID情報を紐付けます。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_connect_did_infos test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_connect_users
  # グループへのユーザーアカウント紐付け
  # グループの所有者、関係者などの管理者としてユーザーアカウントを紐付けます。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_connect_users test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_connect_vc_infos
  # グループへのVC情報紐付け
  # グループにVC情報を紐付けます。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_connect_vc_infos test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_connect_vc_schema
  # グループへのVCスキーマ紐付け
  # グループにVCスキーマを紐付けます。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_connect_vc_schema test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_connect_vp_infos
  # グループへのVP情報紐付け
  # グループにVP情報を紐付けます。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_connect_vp_infos test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_create
  # グループ作成
  # グループ作成に成功しました。
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_disconnect_did_info
  # グループのDID情報紐付け解除
  # グループに紐付いたDID情報の紐付けを解除します。
  # @param id 
  # @param did_info_id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_disconnect_did_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_disconnect_user
  # グループのユーザーアカウント紐付け解除
  # グループに紐付いたユーザーアカウントの紐付けを解除します。
  # @param id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_disconnect_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_disconnect_vc_info
  # グループのVC情報紐付け解除
  # グループに紐付いたVC情報の紐付けを解除します。
  # @param id 
  # @param vc_info_id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_disconnect_vc_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_disconnect_vc_schema
  # グループのVCスキーマ紐付け解除
  # グループに紐付いたVCスキーマの紐付けを解除します。
  # @param id 
  # @param vc_schema_id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_disconnect_vc_schema test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_disconnect_vp_info
  # グループのVP情報紐付け解除
  # グループに紐付いたVP情報の紐付けを解除します。
  # @param id 
  # @param vp_info_id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_disconnect_vp_info test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_find_all
  # グループ一覧取得
  # グループを一覧として値を返します。
  # @param [Hash] opts the optional parameters
  # @option opts [BigDecimal] :page (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
  # @option opts [BigDecimal] :limit (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
  # @option opts [String] :name (任意)グループの名前。 例: \&quot;Group Project1\&quot;
  # @option opts [String] :status (任意)グループのステータス。 例: \&quot;active\&quot;
  # @return [GroupsResponseDto]
  describe 'groups_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_find_one
  # グループ詳細取得
  # リクエストパラメータのidで指定された単一の管理者アカウントの詳細情報の値を返します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_find_one test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_remove
  # グループ停止
  # リクエストパラメータのidで指定された単一のグループを停止します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'groups_controller_remove test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for groups_controller_update
  # グループ更新
  # リクエストパラメータのidで指定された単一のグループ情報を更新します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GroupResponseDto]
  describe 'groups_controller_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
