=begin
#iDroit Dashboard Admin API

#     これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   

OpenAPI spec version: 0.9.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::UsersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UsersApi' do
  before do
    # run before each test
    @instance = SwaggerClient::UsersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UsersApi' do
    it 'should create an instance of UsersApi' do
      expect(@instance).to be_instance_of(SwaggerClient::UsersApi)
    end
  end

  # unit tests for users_controller_create
  # ユーザーアカウント作成
  # 新規ユーザーアカウントを作成します。
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [UserResponseDto]
  describe 'users_controller_create test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_export_key
  # アカウントへの鍵のメール送信
  # クライアントアカウントに紐付いたDIDの鍵情報をメールで送信し、共有します。
  # @param id 
  # @param key_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_export_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_find_all
  # ユーザーアカウント一覧取得
  # ユーザーアカウントを一覧として値を返します。
  # @param [Hash] opts the optional parameters
  # @option opts [BigDecimal] :page (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
  # @option opts [BigDecimal] :limit (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
  # @option opts [String] :name (任意) 例: \&quot;Jhon Doe\&quot;
  # @option opts [String] :email (任意) 例: \&quot;client1@email.com\&quot;
  # @option opts [String] :status (任意) 例: \&quot;active\&quot;
  # @option opts [String] :role (任意) 例: \&quot;client\&quot;
  # @option opts [BOOLEAN] :need_activate_flow (任意) 例: true, false
  # @return [UsersResponseDto]
  describe 'users_controller_find_all test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_find_one
  # ユーザーアカウント詳細取得
  # リクエストパラメータのidで指定された単一の管理者アカウントの詳細情報の値を返します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [UserResponseDto]
  describe 'users_controller_find_one test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_invite
  # ユーザーアカウントへのアカウント有効化メール送信
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_invite test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_register_user_did
  # Get the count of clients
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_register_user_did test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_registration
  # ユーザーアカウントへのアカウント有効化、登録フロー
  # @param body 
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_registration test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_remove
  # ユーザーアカウント停止
  # リクエストパラメータのidで指定された単一のユーザーアカウントを停止します。
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_remove test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_send_did
  # アカウントへのDIDのメール送信
  # アカウントに紐付いたDIDをメールで送信し、共有します。
  # @param id 
  # @param did_info_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_send_did test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_send_key
  # アカウントへのDIDのメール送信
  # アカウントに紐付いたDIDをメールで送信し、共有します。
  # @param id 
  # @param did_info_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_send_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_send_vc
  # アカウントへのVCのメール送信
  # アカウントに紐付いたVCをメールで送信し、共有します。
  # @param id 
  # @param vc_info_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'users_controller_send_vc test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for users_controller_update
  # ユーザーアカウント更新
  # リクエストパラメータのidで指定された単一のユーザーアカウント情報を更新します。
  # @param body 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [UserResponseDto]
  describe 'users_controller_update test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
