=begin
#iDroit Dashboard Admin API

#     これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   

OpenAPI spec version: 0.9.2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.68
=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/add_label_to_badge_dto'
require 'swagger_client/models/add_label_to_did_info_dto'
require 'swagger_client/models/add_label_to_vc_info_dto'
require 'swagger_client/models/add_label_to_vp_info_dto'
require 'swagger_client/models/all_of_badge_response_dto_vc_info'
require 'swagger_client/models/all_of_badge_response_dto_vc_schema'
require 'swagger_client/models/all_of_badge_vc_info'
require 'swagger_client/models/all_of_badge_vc_schema'
require 'swagger_client/models/all_of_did_info_created_by'
require 'swagger_client/models/all_of_did_info_response_dto_did_info'
require 'swagger_client/models/all_of_did_info_user'
require 'swagger_client/models/all_of_did_info_vp_infos'
require 'swagger_client/models/all_of_file_created_by'
require 'swagger_client/models/all_of_file_response_dto_created_by'
require 'swagger_client/models/all_of_file_vc_schema'
require 'swagger_client/models/all_of_group_created_by'
require 'swagger_client/models/all_of_group_response_dto_created_by'
require 'swagger_client/models/all_of_user_created_by'
require 'swagger_client/models/all_of_user_response_dto_created_by'
require 'swagger_client/models/all_of_vc_context_vc_schema'
require 'swagger_client/models/all_of_vc_info_badge'
require 'swagger_client/models/all_of_vc_info_created_by'
require 'swagger_client/models/all_of_vc_info_response_dto_vc_info'
require 'swagger_client/models/all_of_vc_info_user'
require 'swagger_client/models/all_of_vc_info_vc_schema'
require 'swagger_client/models/all_of_vc_schema_created_by'
require 'swagger_client/models/all_of_vc_schema_file'
require 'swagger_client/models/all_of_vc_schema_property_vc_schema'
require 'swagger_client/models/all_of_vc_schema_response_dto_created_by'
require 'swagger_client/models/all_of_vc_schema_response_dto_file'
require 'swagger_client/models/all_of_verification_created_by'
require 'swagger_client/models/all_of_verification_response_dto_created_by'
require 'swagger_client/models/all_of_verification_response_dto_vc_info'
require 'swagger_client/models/all_of_verification_response_dto_vp_info'
require 'swagger_client/models/all_of_verification_vc_info'
require 'swagger_client/models/all_of_verification_vp_info'
require 'swagger_client/models/all_of_verifications_response_dto_links'
require 'swagger_client/models/all_of_verifications_response_dto_meta'
require 'swagger_client/models/all_of_vp_info_created_by'
require 'swagger_client/models/all_of_vp_info_detail_dto_vp_info'
require 'swagger_client/models/all_of_vp_info_did_info'
require 'swagger_client/models/all_of_vp_info_user'
require 'swagger_client/models/badge'
require 'swagger_client/models/badge_response_dto'
require 'swagger_client/models/badges_file_body'
require 'swagger_client/models/badges_response_dto'
require 'swagger_client/models/connect_did_infos_dto'
require 'swagger_client/models/connect_users_dto'
require 'swagger_client/models/connect_vc_infos_dto'
require 'swagger_client/models/connect_vc_schemas_dto'
require 'swagger_client/models/connect_vp_infos_dto'
require 'swagger_client/models/create_badge_dto'
require 'swagger_client/models/create_did_dto'
require 'swagger_client/models/create_group_dto'
require 'swagger_client/models/create_user_dto'
require 'swagger_client/models/create_vc_info_dto'
require 'swagger_client/models/create_vc_schema_dto'
require 'swagger_client/models/create_vp_info_dto'
require 'swagger_client/models/did_info'
require 'swagger_client/models/did_info_response_dto'
require 'swagger_client/models/did_infos_response_dto'
require 'swagger_client/models/file'
require 'swagger_client/models/file_response_dto'
require 'swagger_client/models/files_response_dto'
require 'swagger_client/models/generate_did_dto'
require 'swagger_client/models/generate_vp_dto'
require 'swagger_client/models/get_profile_response_dto'
require 'swagger_client/models/group'
require 'swagger_client/models/group_response_dto'
require 'swagger_client/models/groups_response_dto'
require 'swagger_client/models/issue_vc_info_dto'
require 'swagger_client/models/link_dto'
require 'swagger_client/models/mail'
require 'swagger_client/models/mails_response_dto'
require 'swagger_client/models/meta_dto'
require 'swagger_client/models/register_did_dto'
require 'swagger_client/models/registration_process_dto'
require 'swagger_client/models/resolve_did_dto'
require 'swagger_client/models/resolve_did_response_dto'
require 'swagger_client/models/send_mail_batch_dto'
require 'swagger_client/models/send_mail_dto'
require 'swagger_client/models/setting'
require 'swagger_client/models/setting_list_response_dto'
require 'swagger_client/models/setting_response_dto'
require 'swagger_client/models/sign_in_dto'
require 'swagger_client/models/sign_in_response_dto'
require 'swagger_client/models/update_vc_info_dto'
require 'swagger_client/models/update_vc_schema_dto'
require 'swagger_client/models/upload_vc_dto'
require 'swagger_client/models/upload_vp_dto'
require 'swagger_client/models/user'
require 'swagger_client/models/user_response_dto'
require 'swagger_client/models/user_token'
require 'swagger_client/models/users_response_dto'
require 'swagger_client/models/v1_files_body'
require 'swagger_client/models/vc_context'
require 'swagger_client/models/vc_info'
require 'swagger_client/models/vc_info_response_dto'
require 'swagger_client/models/vc_infos_response_dto'
require 'swagger_client/models/vc_schema'
require 'swagger_client/models/vc_schema_property'
require 'swagger_client/models/vc_schema_response_dto'
require 'swagger_client/models/vc_schemas_response_dto'
require 'swagger_client/models/verification'
require 'swagger_client/models/verification_dto'
require 'swagger_client/models/verification_response_dto'
require 'swagger_client/models/verifications_response_dto'
require 'swagger_client/models/verifiy_badge_file_reponse_dto'
require 'swagger_client/models/verifiy_badge_reponse_dto'
require 'swagger_client/models/verify_badge_dto'
require 'swagger_client/models/vp_info'
require 'swagger_client/models/vp_info_detail_dto'
require 'swagger_client/models/vp_info_response_dto'

# APIs
require 'swagger_client/api/auth_api'
require 'swagger_client/api/badges_api'
require 'swagger_client/api/did_infos_api'
require 'swagger_client/api/files_api'
require 'swagger_client/api/groups_api'
require 'swagger_client/api/health_api'
require 'swagger_client/api/mails_api'
require 'swagger_client/api/settings_api'
require 'swagger_client/api/users_api'
require 'swagger_client/api/vc_infos_api'
require 'swagger_client/api/vc_schemas_api'
require 'swagger_client/api/verifications_api'
require 'swagger_client/api/vp_infos_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
